/*
    HRNexus employee code sequence.

    Employee codes are generated by the application from emp.EmployeeCodeSequence
    using the format HRN-EMP-{number:D4}. Existing employee codes are preserved.
*/

SET NOCOUNT ON;

DECLARE @MaxExistingEmployeeCodeNumber int;

SELECT @MaxExistingEmployeeCodeNumber =
    MAX(TRY_CONVERT(int, SUBSTRING(EmployeeCode, LEN(N'HRN-EMP-') + 1, 50)))
FROM emp.Employee
WHERE EmployeeCode LIKE N'HRN-EMP-[0-9]%';

DECLARE @NextEmployeeCodeNumber bigint = ISNULL(@MaxExistingEmployeeCodeNumber, 0) + 1;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.sequences seq
    INNER JOIN sys.schemas schema_info
        ON schema_info.schema_id = seq.schema_id
    WHERE schema_info.name = N'emp'
      AND seq.name = N'EmployeeCodeSequence'
)
BEGIN
    DECLARE @CreateSequenceSql nvarchar(max) =
        N'CREATE SEQUENCE emp.EmployeeCodeSequence AS int ' +
        N'START WITH ' + CONVERT(nvarchar(20), @NextEmployeeCodeNumber) + N' ' +
        N'INCREMENT BY 1 ' +
        N'MINVALUE 1 ' +
        N'NO MAXVALUE ' +
        N'CACHE 20;';

    EXEC sys.sp_executesql @CreateSequenceSql;
END
ELSE
BEGIN
    DECLARE @CurrentSequenceValue bigint;

    SELECT @CurrentSequenceValue = TRY_CONVERT(bigint, seq.current_value)
    FROM sys.sequences seq
    INNER JOIN sys.schemas schema_info
        ON schema_info.schema_id = seq.schema_id
    WHERE schema_info.name = N'emp'
      AND seq.name = N'EmployeeCodeSequence';

    IF @CurrentSequenceValue IS NOT NULL
       AND @CurrentSequenceValue < @NextEmployeeCodeNumber
    BEGIN
        DECLARE @AlterSequenceSql nvarchar(max) =
            N'ALTER SEQUENCE emp.EmployeeCodeSequence RESTART WITH ' +
            CONVERT(nvarchar(20), @NextEmployeeCodeNumber) + N';';

        EXEC sys.sp_executesql @AlterSequenceSql;
    END;
END;
